Repository Corrupteddisk/SpotifycloneWeb, pull requests merged in 2024-01, with the labels that each got.

#34 changed audio controls ui
  index.html
  style.css
Labels: apertre, medium

#40 Footer and details of singer added
  covers/1.jpg
  covers/10.jpg
  covers/2.jpg
  covers/3.jpg
  covers/4.jpg
  covers/5.jpg
  covers/6.jpg
  covers/7.jpg
  covers/8.jpg
  covers/9.jpg
  covers/Spotify-White-Logo.png
  covers/a-singh.jpg
  covers/arijit.jpg
  covers/fb.png
  covers/ig.png
  covers/twt.png
  index.html
  style.css
Labels: apertre, easy

#45 Fixed the timestamps
  index.html
Labels: apertre, medium

#47 Make the navbar responsive
  index.html
  navbar.js
  style.css
Labels: apertre, medium

#53 solved the issue #31
  apple.png
  facebook.png
  google.png
  images/All Out 2010s.jpg
  images/All Out 80s.jpg
  images/Beats to think to.jpg
  images/Chill Hits.jpg
  images/Deep Focus.jpg
  images/Focus Flow.jpg
  images/Instrumental Study.jpg
  images/Peaceful Piano.jpg
  images/RapCaviar.jpg
  images/Reading Adventure.jpg
  images/Rock Classics.jpg
  images/Spotify Logo.png
  images/SpotifyClone.png
  images/Spotify_favicon.png
  images/The Sound of Bengaluru.jpg
  images/The Sound of Chennai.jpg
  images/The Sound of Delhi.jpg
  images/The Sound of Hyderabad.jpg
  images/The Sound of Kolkata.jpg
  images/The Sound of Mumbai.jpg
  images/Today's Top Hits.jpg
  images/Viva Latino.jpg
  images/Workday Lounge.jpg
  login.css
  login.html
  main.css
  main.html
  spo-logo.png
Labels: apertre, hard

#56 fixed song pausing issue from list
  script1.js
  style.css
Labels: apertre, hard

#57 Fixed icon bug of song list
  index.html
  script1.js
Labels: apertre, medium

#58 added time duration
  index.html
  script1.js
  style.css
Labels: apertre, medium

#63 song select on click song div
  script1.js
  style.css
Labels: apertre, hard

#67 Arijit hover
  index.html
  style.css
Labels: apertre, medium

#75 Added responsiveness for home page for narrow screens
  home-page/home.css
  home-page/home.html
Labels: apertre, hard

#99 Modified about page
  About.css
  About.html
  about/about.css
  about/about.html
  about/ari-si.jpg
  about/as.jpg
  index.html
Labels: apertre, hard

#80 Make the Navbar Responsive
  index.html
  navbar.js
  style.css
Labels: apertre, hard

#109 bugfixing signup and login redirection
  index.html
Labels: apertre, hard

#113 Nav bar index
  index.html
  main.css
  main.html
  style.css
Labels: apertre, hard

#115 Added Favicon
  about/favicon.png
  favicon.png
  home-page/favicon.png
  home-page/home.html
  index.html
  main.html
  sign-in-and-login/favicon.png
  sign-in-and-login/login_form.html
  sign-in-and-login/sign_up_form.html
  support.html
Labels: apertre, medium

#116 Improved Ui of Signup Page
  sign-in-and-login/loginbg.jpg
  sign-in-and-login/loginbg.png
  sign-in-and-login/sign_up_form.css
  sign-in-and-login/sign_up_form.html
Labels: apertre, hard

#120 made a sign-up page (#91)
  signup.css
  signup.html
Labels: apertre, hard

#135 Added designer scrollbars
  about/about.css
  bengali/bengali.css
  home-page/home.css
  main.css
  party/party.css
  romantic/romantic.css
  sad/sad.css
  sign-in-and-login/login_form.css
  sign-in-and-login/sign_up_form.css
  style.css
  support.css
Labels: apertre, medium

#138 Make the website responsive
  index.html
  style.css
Labels: apertre, medium

#139 Make the About Page Responsive for all device
  about/Aboutnavbar.js
  about/about.css
  about/about.html
  index.html
Labels: apertre, medium

#142 Linked the support page
  index.html
  support.html
Labels: apertre, easy

#143 Make the Sign in and Sign up page resopnsive for all device
  sign-in-and-login/login_form.css
  sign-in-and-login/login_form.html
  sign-in-and-login/sign_up_form.css
Labels: apertre, medium

#146 AOS effects added
  bengali/bengali.html
  index.html
  party/party.html
  romantic/romantic.html
  sad/sad.html
Labels: apertre, easy

#147 Add volume option in the Play button
  index.html
  script1.js
  style.css
Labels: apertre, easy

#159 Readme
  README.md
Labels: apertre, easy

#152 Card Responsive issue Solve
  style.css
Labels: apertre, easy

#154 added footer in main.html file(#127)
  main.css
  main.html
  signup.css
  signup.html
Labels: apertre, easy

#162 added replay and shuffle
  .vscode/settings.json
  bengali/bengali.html
  bengali/bengali.js
  index.html
  party/party.html
  party/party.js
  romantic/romantic.html
  romantic/romantic.js
  sad/sad.html
  sad/sad.js
  script1.js
  style.css
Labels: apertre, medium

#165 Sign-in Sign-up Form Validation
  sign-in-and-login/login_form.css
  sign-in-and-login/login_form.html
  sign-in-and-login/login_form.js
  sign-in-and-login/signUp.js
  sign-in-and-login/sign_up_form.css
  sign-in-and-login/sign_up_form.html
Labels: apertre, medium

#161 added signup with google, facebook & apple options in the signup page(#155)
  signup.css
  signup.html
  support.html
Labels: apertre, easy

#177 UI improvement
  sign-in-and-login/login_form.css
  sign-in-and-login/login_form.html
  sign-in-and-login/sign_up_form.css
  sign-in-and-login/sign_up_form.html
Labels: apertre, easy

#182 Reduced size of back to top button
  style.css
Labels: apertre, easy

#176 Add Form validation Feature
  about/ContactFormvalidation.js
  about/about.css
  about/about.html
  sign-in-and-login/login_form.css
  sign-in-and-login/login_form.html
  sign-in-and-login/login_form.js
  sign-in-and-login/sign_up_form.css
  sign-in-and-login/sign_up_form.html
Labels: apertre, easy

#189 Update About Page Footer
  Scrollback.js
  about/Scroll.js
  about/about.css
  about/about.html
  about/fb.png
  about/ig.png
  about/twt.png
  main.css
  main.html
Labels: apertre, easy

#185 added cover image at control setion
  bengali/bengali.js
  index.html
  party/party.js
  romantic/romantic.js
  sad/sad.js
  script1.js
  style.css
Labels: apertre, medium

#187 made changes in the footer of the support page(#173)
  support.css
  support.html
Labels: apertre, easy

#192 Genre hover
  bengali/bengali.html
  index.html
  new_releases/new-release.html
  party/party.html
  romantic/romantic.html
  sad/sad.html
  style.css
Labels: apertre, medium

#194 added responsive medium width device
  style.css
Labels: apertre, easy

#199 #95 issue solved
  about/about.css
  about/about.html
  about/about.js
  about/moon-icon.png
  about/moon-icon2.png
  about/sun-icon.png
  home-page/home.css
  home-page/home.html
  home-page/home.js
  home-page/moon-icon.png
  home-page/sun-icon.png
  index.html
  moon-icon.png
  moon-icon2.png
  script1.js
  sign-in-and-login/moon-icon.png
  sign-in-and-login/sun-icon.png
  style.css
  sun-icon.png
  support.css
  support.html
  support.js
Labels: apertre, hard

#198 Hober Effect
  index.html
  sign-in-and-login/login_form.css
  sign-in-and-login/login_form.html
  sign-in-and-login/sign_up_form.css
  sign-in-and-login/sign_up_form.html
  style.css
Labels: apertre, easy

#200 Update Footer of Main.html Page
  main.css
  main.html
Labels: apertre, easy

#210 Add Links in all Navbar menu
  about/about.html
Labels: apertre, easy

#213 signup login favicon corrected
  sign-in-and-login/login_form.html
  sign-in-and-login/sign_up_form.html
Labels: apertre, easy

#215 Added search box in all genres
  bengali/bengali.html
  index.html
  new_releases/new-release.html
  party/party.html
  romantic/romantic.html
  sad/sad.html
  style.css
Labels: apertre, medium

#216 Added light/dark mode in all genres
  bengali/bengali.html
  bengali/bengali.js
  new_releases/new-release.html
  new_releases/new-release.js
  party/party.html
  party/party.js
  romantic/romantic.html
  romantic/romantic.js
  sad/sad.html
  sad/sad.js
Labels: apertre, easy

#217 made light theme better
  bengali/bengali.html
  index.html
  new_releases/new-release.html
  party/party.html
  romantic/romantic.html
  sad/sad.html
  style.css
Labels: apertre, medium
